#!/usr/bin/env bash

# From:
# https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f

if [ -x "$(command -v brew)" ]; then
  brew bundle dump --force
  echo "Brewfile has been created"
else
  echo "Homebrew is not installed"
fi
