live_config_reload = true

[env]
TERM = "screen-256color"

[window]
startup_mode = "Fullscreen"

[scrolling]
history = "10000"

[font]
normal = { family = "DejaVuSansM Nerd Font", style = "Regular" }
bold = { family = "DejaVuSansM Nerd Font", style = "Bold" }
italic = { family = "DejaVuSansM Nerd Font", style = "Italic" }
bold_italic = { family = "DejaVuSansM Nerd Font", style = "Bold Italic" }
size = 16.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block" }
